### ISSUE TITLE
Element Mass Table Incomplete

### ISSUE THREAD

**Issue by jmmitc06** [shuzhao-li/mass2chem#7]
The mass table for elements in formula.py does not contain some elements, such as Pt. This could be generate automatically from NIST or other source. I have a script for doing that somewhere that I can provide so we can update this.

**Comment by jmmitc06** [comment]
This has been fixed on a local branch on my machine; however, I do not have permission to push to this repository. Please add me @gmhhope or @shuzhao-li and I can push the change.

**Comment by shuzhao-li** [comment]
Merged.
